Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 27, in main
    ami = createAMI(instance)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 149, in createAMI
    NoReboot=True
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAMIName.Duplicate) when calling the CreateImage operation: AMI name BACKUP-RT 001/B/001-29082019-221003(CEST) is already in use by AMI ami-00a9f599e8c47fb38
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 217, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 231, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0a4a0a8d6ea57da93 is currently in use by ami-0f7c44f57ee189820
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 217, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 231, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0ed28dba215df7f82 is currently in use by ami-033aae5fdb4b9f940
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 217, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 231, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0d575d1f21136c7a8 is currently in use by ami-0ca4516ec16419deb
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 217, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 231, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-09a36154eca4233ac is currently in use by ami-0e1cfe2b39d8095ef
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 27, in main
    ami = createAMI(instance)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 149, in createAMI
    NoReboot=True
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: <exception str() failed>
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 217, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 231, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0997668f974e084d2 is currently in use by ami-0b32015686c069bcc
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 221, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 235, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-09dcf7a6eeacc4dee is currently in use by ami-0f5bdd6836aea80f2
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 27, in main
    ami = createAMI(instance)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 149, in createAMI
    NoReboot=True
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateImage operation: Invalid value 'i-0c86be32baafc5a40' for instanceId. Instance does not have a volume attached at root (/dev/xvda)
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 221, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 235, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0965e24daf79edab0 is currently in use by ami-0560a3ac9d705b9fc
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 221, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 235, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-01456203efceb4ebe is currently in use by ami-0d586276267f25e4d
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 221, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 233, in deleteExpiredSnapshots
    for snapshot in snapshots:
  File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 135, in _send_request
    request, operation_model, context)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 167, in _get_response
    request, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/usr/lib/python2.7/site-packages/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1137, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 42, in <module>
    main()
  File "/usr/local/scripts/brockenSpectre/brockenSpectre.py", line 32, in main
    expireImages(expireThisImages)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 221, in expireImages
    deleteExpiredSnapshots(image.id)
  File "/usr/local/scripts/brockenSpectre/imageLibraries.py", line 235, in deleteExpiredSnapshots
    snapshot.delete()
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-02dac31a3cf84e585 is currently in use by ami-0282fc69916e433d5
